name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: MarcoALR
          outputs: |
            ./dist/github-contribution-grid-snake-dark.svg?color_snake=47f7d7&color_dots=#444444,#6c71c4,#ffffff
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate github-contribution-grid-snake.svg"
          add: "dist/*.svg"
