# .github/workflows/snake.yml
name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # todo dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate snake svg
        uses: Platane/snk@master
        with:
          github_user_name: MarcoALR
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          color_snake: "#00FF7F" # cobra verde
          color_dots: "#0d1117,#161b22,#21262d,#30363d,#8b949e" # quadradinhos escuros
      
      - name: Push the svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
