name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: MarcoALR
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push SVG to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate snake svg"
          add: "dist/*.svg"
          default_author: github_actions
          new_branch: output
